export type MenuItem = { name: string; desc: string; price: string };

export const fullMenu: Record<string, MenuItem[]> = {
  "Mic dejun": [
    { name: "Mic dejun grecesc", desc: "200g — omletă, brânză, roșii, măsline, sos tzatziki, pâine prăjită", price: "30" },
    { name: "Mic dejun englezesc", desc: "250g — ouă, bacon, cârnați, ciuperci, cartofi prăjiți, roșii, pâine prăjită", price: "30" },
    { name: "Cașcaval pane", desc: "200g — cașcaval, ouă, făină, pesmet", price: "25" },
    { name: "Omletă cu șuncă și cașcaval", desc: "150g", price: "20" },
    { name: "Omletă cu ciuperci și cașcaval", desc: "150g", price: "20" },
    { name: "Omletă simplă", desc: "100g", price: "15" },
  ],
  Antreuri: [
    { name: "Bruschete cu roșii", desc: "8 buc / 180g — pâine prăjită, parmezan, roșii, usturoi", price: "20" },
    { name: "Bruschete mixte", desc: "8 buc / 180g — pâine prăjită, somon prăjit, măsline, roșii", price: "20" },
    { name: "Platou brânzeturi", desc: "240g — brânză telemea, gorgonzola, parmezan, cașcaval afumat, roșii", price: "30" },
    { name: "Aperitiv mixt", desc: "300g — cârnați afumați, bacon, șuncă presată, crochete carne, fingers pui, cașcaval, roșii, castraveți, măsline", price: "35" },
    { name: "Aperitiv Ocaua", desc: "200g — salam vara extra, șuncă presată, cârnați afumați, bacon, cașcaval, roșii, castraveți, măsline", price: "35" },
    { name: "Mămăligă cu brânză și smântână", desc: "300g", price: "30" },
    { name: "Salată Caprese", desc: "100g — roșii, busuioc, ulei, măsline, mozzarela", price: "30" },
    { name: "Salată bulgărească", desc: "200g — salată verde, roșii, castraveți, șuncă presată, ardei gras, ceapă, crutoane, ou, telemea, măsline", price: "30" },
    { name: "Salată de pui", desc: "200g — salată verde, roșii, castraveți, piept pui, ardei gras, ceapă, crutoane, parmezan", price: "30" },
    { name: "Salată cu ton", desc: "200g — salată verde, ton, ceapă, castraveți, porumb, ardei gras, măsline, lămâie, crutoane", price: "35" },
    { name: "Salată Caesar", desc: "200g — piept de pui, roșii, castraveți, ceapă, salată verde, sos Caesar, crutoane", price: "30" },
    { name: "Salată prosciuto", desc: "200g", price: "30" },
  ],
  Ciorbe: [
    { name: "Ciorbă de legume", desc: "300g", price: "20" },
    { name: "Ciorbă de pui", desc: "70/230g", price: "25" },
    { name: "Ciorbă de perișoare", desc: "70/230g", price: "25" },
    { name: "Ciorbă de văcuță", desc: "70/230g", price: "25" },
    { name: "Ciorbă de burtă", desc: "70/230g", price: "28" },
    { name: "Ciorbă rădăuțeană", desc: "70/230g", price: "28" },
  ],
  "Preparate de vită": [
    { name: "Mușchi de vită la grătar", desc: "230g", price: "95" },
    { name: "Mușchi de vită cu sos alb", desc: "250g", price: "95" },
    { name: "Mușchi de vită în prosciuto", desc: "250g — mușchi de vită, prosciuto", price: "95" },
    { name: "Antricot de vită / bistecca", desc: "250g", price: "95" },
  ],
  "Preparate de porc": [
    { name: "Ceafă de porc la grătar", desc: "200g", price: "30" },
    { name: "Tochitură moldovenească", desc: "300g — carne de porc, cârnați, ciuperci, sos de roșii, ou, brânză rasă, usturoi", price: "35" },
    { name: "Mușchiuleț învelit în bacon cu sos de ciuperci", desc: "200g — mușchi de porc, sos de ciuperci, bacon", price: "60" },
    { name: "Mușchiuleț de porc la grătar", desc: "200g", price: "30" },
    { name: "Cotlet de porc la grătar", desc: "200g", price: "30" },
    { name: "Șnițel de porc", desc: "200g — pulpă de porc, pesmet, ou, făină", price: "30" },
    { name: "Cârnați de porc", desc: "200g", price: "25" },
    { name: "Scăricică de porc la grătar", desc: "200g — coastă întreagă", price: "55" },
    { name: "Piept de porc la grătar", desc: "250g", price: "35" },
  ],
  "Preparate de pui": [
    { name: "Pulpă de pui dezosată la grătar", desc: "200g", price: "25" },
    { name: "Frigărui pui", desc: "200g — piept de pui, roșii, ardei, ceapă", price: "25" },
    { name: "Șnițel de pui", desc: "200g — piept de pui, ou, făină, pesmet", price: "30" },
    { name: "Ficat de pui", desc: "200g", price: "25" },
    { name: "Saramură de pui", desc: "200g — cu mămăliguță", price: "25" },
    { name: "Aripioare de pui picante", desc: "200g", price: "25" },
    { name: "Piept de pui la grătar", desc: "250g", price: "25" },
    { name: "Ciulama de pui", desc: "250g — cu ciuperci, mămăligă și smântână", price: "25" },
    { name: "Cordon Bleu", desc: "200g — piept de pui, șuncă presată, cașcaval, pesmet, ou", price: "30" },
    { name: "Fingers de pui", desc: "150g", price: "25" },
  ],
  "Preparate de pește și fructe de mare": [
    { name: "Somon la grătar", desc: "200g", price: "60" },
    { name: "Saramură de crap cu mămăliguță", desc: "300g", price: "45" },
    { name: "Păstrăv la grătar", desc: "250g", price: "55" },
    { name: "Midii cu sos", desc: "150g", price: "35" },
    { name: "Creveți în sos", desc: "150g", price: "75" },
    { name: "Midii la tigaie", desc: "200g", price: "35" },
    { name: "Platou cu fructe de mare", desc: "400g — creveți, calamar pane, midii, sos", price: "140" },
  ],
  "Specialități & platouri": [
    { name: "Quesadilla", desc: "300g — mozzarella, piept de pui, ciuperci", price: "35" },
    { name: "Platou Ocaua", desc: "2 pers / 400g — pulpă de pui, ceafă, cârnați, mici, coastă de porc, cartofi țărănești, salată", price: "140" },
    { name: "Platou tradițional", desc: "3 pers / 900g — pulpă de pui, ceafă, cârnați, coastă de porc, mici, cartofi țărănești, brânză, mămăligă, salată", price: "240" },
    { name: "Pastramă de oaie", desc: "250g — mămăliguță și acritură", price: "65" },
    { name: "Cotlet de berbecuț", desc: "200g", price: "90" },
    { name: "Bulz moldovenesc", desc: "300g — brânză rasă, carne porc, cârnați, mămăligă, ou", price: "35" },
    { name: "Mici cu pâine și muștar", desc: "1 buc / 50g", price: "5" },
  ],
  Pizza: [
    { name: "Pizza Ocaua", desc: "blat pizza, sos pizza, mozzarella, șuncă presată, salam, cârnați, măsline, ardei gras", price: "28" },
    { name: "Pizza Capricioasa", desc: "blat pizza, sos pizza, mozzarella, șuncă presată, ardei gras, ciuperci", price: "25" },
    { name: "Pizza Prosciuto cu ciuperci", desc: "blat pizza, sos pizza, mozzarella, șuncă presată, ciuperci", price: "25" },
    { name: "Pizza Ton", desc: "blat pizza, sos pizza, ton, ceapă, măsline, lămâie", price: "28" },
    { name: "Pizza Vegetariană", desc: "blat pizza, sos pizza, mozzarella, ciuperci, ardei gras, măsline", price: "25" },
    { name: "Pizza Post", desc: "blat pizza, sos, cașcaval de post, ciuperci, ardei gras, măsline, porumb, roșii", price: "20" },
    { name: "Pizza Rustica", desc: "blat pizza, sos pizza, mozzarella, piept de pui afumat", price: "28" },
    { name: "Pizza cu Cartofi", desc: "blat pizza, sos pizza, mozzarella, piept de pui afumat", price: "28" },
    { name: "Pizza Diavola", desc: "blat pizza, mozzarella, salam crud uscat, pastă ardei iute", price: "25" },
    { name: "Pizza Quatro Formaggi", desc: "blat pizza, sos, mozzarella, cașcaval afumat, gorgonzola, parmezan, ardei gras", price: "28" },
    { name: "Pizza Quatro Stagionni", desc: "blat pizza, sos pizza, ciuperci, șuncă presată, salam, măsline, mozzarella", price: "28" },
    { name: "Pizza Margherita", desc: "blat pizza, sos pizza, busuioc, roșii, extra mozzarella", price: "25" },
    { name: "Calzone", desc: "blat pizza, sos pizza, mozzarella, șuncă presată, ciuperci", price: "30" },
  ],
  Paste: [
    { name: "Spaghete bolognese", desc: "200g — sos bolognese, mozzarella, carne tocată vită", price: "30" },
    { name: "Spaghete vegetariene", desc: "200g — busuioc, sos roșii, mozzarella", price: "25" },
    { name: "Carbonara", desc: "200g — spaghetti, smântână, ou, bacon, parmezan", price: "30" },
    { name: "Spaghete cu fructe de mare", desc: "200g — sos de vin alb, lămâie, busuioc", price: "35" },
    { name: "Spaghete cu ton", desc: "200g", price: "30" },
    { name: "Penne de post", desc: "200g — legume trase la tigaie", price: "25" },
    { name: "Penne quatro formaggi", desc: "200g — smântână, gorgonzola, mozzarella, parmezan, cașcaval afumat", price: "30" },
    { name: "Penne cu roșii și pui", desc: "200g — piept de pui, roșii, parmezan", price: "25" },
  ],
  "Garnituri / Salate": [
    { name: "Cartofi", desc: "150g", price: "10" },
    { name: "Cartofi țărănești", desc: "150g", price: "10" },
    { name: "Buturugă din cartofi gratinati", desc: "100g", price: "10" },
    { name: "Piure de cartofi", desc: "150g", price: "10" },
    { name: "Buchet de legume la tigaie", desc: "150g", price: "10" },
    { name: "Ciuperci sote", desc: "150g", price: "10" },
    { name: "Broccoli și morcovi", desc: "150g", price: "10" },
    { name: "Orez cu legume", desc: "150g", price: "10" },
    { name: "Salată asortată de sezon", desc: "200g", price: "10" },
    { name: "Salată verde", desc: "150g", price: "8" },
    { name: "Salată de varză albă", desc: "150g", price: "8" },
    { name: "Salată mix murături", desc: "200g", price: "8" },
    { name: "Salată gogoșari la oțet", desc: "200g", price: "10" },
    { name: "Salată ardei copți", desc: "200g", price: "15" },
  ],
  "Cafea / Ceaiuri": [
    { name: "Cafea espresso", desc: "30/70ml", price: "10" },
    { name: "Cafea frappe", desc: "200ml", price: "20" },
    { name: "Cappuccino", desc: "100ml", price: "15" },
    { name: "Latte machiato", desc: "150ml", price: "20" },
    { name: "Ciocolată caldă", desc: "150ml", price: "15" },
    { name: "Ceai negru", desc: "150ml", price: "10" },
    { name: "Ceai verde", desc: "150ml", price: "10" },
    { name: "Ceai fructe", desc: "150ml", price: "10" },
  ],
  "Răcoritoare": [
    { name: "Apă minerală plată / carbogazoasă", desc: "0.33L", price: "6" },
    { name: "Apă minerală plată / carbogazoasă", desc: "0.75L", price: "10" },
    { name: "Cola / Fanta / Sprite", desc: "0.25L", price: "8" },
    { name: "Cappy", desc: "0.25L", price: "10" },
    { name: "Schweppes", desc: "0.25L", price: "10" },
    { name: "Power Ice Tea", desc: "0.33L", price: "10" },
    { name: "FuzeTea", desc: "0.25L", price: "10" },
    { name: "Fresh fructe", desc: "0.25L", price: "15" },
    { name: "Limonadă", desc: "0.25L", price: "15" },
    { name: "Aloe Vera", desc: "0.5L", price: "15" },
  ],
  "Cocktails alcoolice": [
    { name: "Daiquiri", desc: "250ml — rom, lime, sirop zahăr", price: "25" },
    { name: "Gin tonic", desc: "200ml — gin, apă tonică, lămâie, gheață", price: "25" },
    { name: "Gin fizz", desc: "180ml — gin, suc de lămâie, sprite", price: "25" },
    { name: "Cuba Libre", desc: "250ml — rom, cola, lime", price: "25" },
    { name: "Screwdriver", desc: "250ml — vodcă, suc portocală", price: "25" },
    { name: "Pina Colada", desc: "rom, lichior de cocos, suc de ananas", price: "25" },
    { name: "Margarita", desc: "tequila, triplu sec, lime", price: "25" },
    { name: "Mojito", desc: "zahăr brun, mentă, apă minerală, lime", price: "25" },
    { name: "Campari Orange", desc: "campari, suc portocală, gheață", price: "25" },
    { name: "Long Island Ice Tea", desc: "vodcă, gin, rom, tequila, triplu sec, cola, lime", price: "25" },
    { name: "Sex on the beach", desc: "vodcă, suc piersici, suc portocale, suc ananas, grenadine", price: "25" },
  ],
  "Cocktails non-alcoolice": [
    { name: "Green apple", desc: "suc mere, lime, zahăr brun, curacao", price: "20" },
    { name: "Red apple", desc: "suc mere, zahăr brun, grenadine", price: "20" },
    { name: "Safe sex on the beach", desc: "suc piersici, suc portocale, grenadine", price: "20" },
  ],
  "Energizante": [
    { name: "Red Bull", desc: "0.25L", price: "15" },
    { name: "Burn", desc: "0.25L", price: "15" },
  ],
  "Băuturi alcoolice": [
    { name: "Vinars Jidvei VSOP", desc: "40ml", price: "15" },
    { name: "Alexandrion 7*", desc: "40ml", price: "15" },
    { name: "Alexandrion 5*", desc: "40ml", price: "10" },
    { name: "Rom Havana Club", desc: "40ml", price: "10" },
    { name: "Chivas Regal", desc: "40ml", price: "20" },
    { name: "Jack Daniel's", desc: "40ml", price: "20" },
    { name: "Ballantines / Teacher's", desc: "40ml", price: "15" },
    { name: "Sheridan's Liqueur", desc: "40ml", price: "10" },
    { name: "Baileys Irish Cream Liqueur", desc: "40ml", price: "10" },
    { name: "Jägermeister", desc: "40ml", price: "10" },
    { name: "Campari", desc: "40ml", price: "10" },
    { name: "Martini / Cinzano", desc: "40ml", price: "10" },
    { name: "Garrone / Angeli", desc: "40ml", price: "10" },
    { name: "Gin", desc: "40ml", price: "10" },
    { name: "Pălincă / Țuică / Afinată", desc: "40ml", price: "10" },
    { name: "Stalinskaya", desc: "40ml", price: "10" },
    { name: "Absolut", desc: "40ml", price: "10" },
  ],
  Bere: [
    { name: "Grolsch", desc: "0.5L", price: "15" },
    { name: "Peroni", desc: "0.5L", price: "15" },
    { name: "Ursus Premium", desc: "0.5L", price: "10" },
    { name: "Ursus Retro nepasteurizat", desc: "0.5L", price: "10" },
    { name: "Ursus fără alcool", desc: "0.5L", price: "10" },
    { name: "Ursus Black", desc: "0.5L", price: "10" },
    { name: "Ursus Cooler F.A", desc: "0.5L", price: "10" },
    { name: "Ursus halbă", desc: "0.4L", price: "8" },
    { name: "Timișoreana nepasteurizată", desc: "0.5L", price: "8" },
    { name: "Heineken", desc: "0.33L / 0.4L", price: "15" },
    { name: "Corona", desc: "0.5L", price: "15" },
  ],
};

export const homeMenu: Record<string, MenuItem[]> = {
  "Mic dejun": fullMenu["Mic dejun"],
  Antreuri: fullMenu.Antreuri.slice(0, 4),
  "Feluri principale": [
    fullMenu["Preparate de vită"][0],
    fullMenu["Preparate de porc"][4],
    fullMenu["Preparate de pui"][6],
    fullMenu["Preparate de pește și fructe de mare"][0],
    fullMenu.Paste[0],
    fullMenu["Specialități & platouri"][0],
  ],
  Băuturi: [
    fullMenu["Cafea / Ceaiuri"][0],
    fullMenu["Cafea / Ceaiuri"][2],
    fullMenu["Cocktails alcoolice"][1],
    fullMenu["Cocktails alcoolice"][6],
    fullMenu["Răcoritoare"][0],
    fullMenu["Răcoritoare"][3],
  ],
};
